clone:
  git:
    image: plugins/git
    # depth: 1
    # tags: true
    # branch: fcp
pipeline:
  phpcs:
    image: chimlon/phpcs
    group: laravel
    commands:
      - phpcs --standard=Framgia --encoding=utf-8 app
  fdsfds:
    image: drillster/drone-email
    host: smtp.gmail.com
    username: xxdangminhtruongxx@gmail.com
    password: 01292007776t
    from: xdangminhtruongx@gmail.com
  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./node_modules
      - ./vendor
    volumes:
      - /tmp/cache:/cache
  # rocketeer:
  #   image: fdplugins/ssh-php:php5
  #   when:
  #     branch: fcp
  #     event: [ push, tag ]
  #   commands:
  #     - php rocketeer.phar deploy --on=staging --no-interaction
# services:
#   mysql:
#     image: mysql
#     environment:
#       MYSQL_DATABASE: homestead_test
#       MYSQL_USER: homestead_test
#       MYSQL_PASSWORD: secret
#       MYSQL_ROOT_PASSWORD: root