clone:
  git:
    image: plugins/git
    # depth: 1
    # tags: true
    # branch: fcp
pipeline:
  phpcs:
    image: chimlon/phpcs
    group: laravel
    commands:
      - echo $$token
      - echo Hava
  notify:
      image: dangminhtruong/drone-chatwork
      token: $$token
      room_id: $$room_id
      message: WELCOME TO CI TEAM!
      status: SUCCESS
      build_id: 17
      repo: dangminhtruong/havana
      author: dangminhruong
      branch: master
      commit_id: e786dr2
      create_at: 2018:16:04
      commit_message: Add Dockerfile
      build_link: https://github.com/dangminhtruong
      when:
        status: [ push, changed, failure ]
  # rocketeer:
  #   image: fdplugins/ssh-php:php5
  #   when:
  #     branch: fcp
  #     event: [ push, tag ]
  #   commands:
  #     - php rocketeer.phar deploy --on=staging --no-interaction
# services:
#   mysql:
#     image: mysql
#     environment:
#       MYSQL_DATABASE: homestead_test
#       MYSQL_USER: homestead_test
#       MYSQL_PASSWORD: secret
#       MYSQL_ROOT_PASSWORD: root