eslint:
  comment: true
  exit_code: 2
  ignore: false
pdepend:
  comment: true
  exit_code: 32512
  ignore: true
phpcpd:
  comment: true
  exit_code: 32512
  ignore: true
phpcs:
  comment: true
  exit_code: 0
  ignore: false
phpmd:
  comment: true
  exit_code: 32512
  ignore: true
phpmetrics:
  comment: true
  exit_code: 32512
  ignore: true
phpunit:
  comment: true
  exit_code: 65280
  ignore: false

