version: '2'

services:
  application:
      container_name: framgia_ci_application
      image: debian
      volumes:
          - ./:/var/www/laravel
  workspace:
      container_name: framgia_ci_workspace
      restart: always
      image: dangminhtruong/dockerlaravel
      volumes_from:
          - application
      tty: true
  nginx:
      container_name: framgia_ci_nginx
      restart: always
      image: framgia/laravel-nginx
      volumes_from:
          - application
      ports:
          - "8000:80"
      links:
          - php-fpm
  mysql:
      container_name: framgia_ci_mysql
      restart: always
      image: mysql:5.7
      expose:
          - "3306"
      environment:
          MYSQL_DATABASE: framgia_ci
          MYSQL_USER: framgia_ci
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: root