build:
  phpunit:
    image: dangminhtruong/dockerlarav:latest
    commands:
    - echo '' | phpcs --standard=Framgia app
    - framgia-ci run --local
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
deploy:
  docker:
    username: octocat
    password: password
    email: xdangminhtruonxg@gmail.com
    repo: dangminhtruong/Havana_Laravel
