build:
  phpunit:
    image: dangminhtruong/dockerlarav:latest
    commands:
    - cp .env.civ3.example .env
    - php artisan config:cache
    - composer install
    - vendor/bin/phpunit
    - framgia-ci test-connect mysql_test 3306 60
    - php artisan migrate --database=mysql
    - framgia-ci run
services:
  mysql:
    imagffe: mysql:5.7
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
  mysql_test:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: homestead_test
      MYSQL_USER: homestead_test
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
cache:
  mount:
    - .git
    - vendor
    - node_modules
deploy:
  docker:
    username: octocat
    password: password
    email: dangminhtruong@gmail.com
    repo: dangminhtruong/Havana_Laravel
